model:
  name: "gpt-3.5-turbo"
  temperature: 0.7

memory:
  max_history: 10
  persistence: true

processing:
  timeout: 30
  max_retries: 3
model:
  name: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000

memory:
  max_history: 10
  persistence: true
  storage_path: "./data/memory.json"

processing:
  timeout: 30
  max_retries: 3
  batch_size: 5

logging:
  level: "INFO"
  file: "./logs/ne_agent.log"
